### PR TITLE
AGPLv3+ license added

### PR DESCRIPTION
**Pull request by comradekingu**

### CODE REVIEW

**Comment by janpf** [comment]
I think, as I use, distribute a service based on and possibly modify https://github.com/mh-/diagnosis-keys/, I noticed I might have to use their license as well: https://github.com/mh-/diagnosis-keys/blob/master/LICENSE.

**Comment by comradekingu** [comment]
@janpf Even better. Works as long as it is something :)

**Comment by janpf** [comment]
True! Thanks for reminding me!

**Comment by stefanb** [comment]
👍 Tnx for sorting this out, will do the same also on our fork https://github.com/sledilnik/ctt

**Pull request merged**
